apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
<<<<<<< HEAD
      - name: node-app
        image: paularinze/node-app:build-12
=======
      - name: node-app
        image: paularinze/node-app:build-12
>>>>>>> 017c06c (Changed App name)
        ports:
        - containerPort: 80